language: python
python:
- '3.6'
- nightly
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  api_key:
    secure: rc/Q7HBqPGIOYkXBDH6yUdwYmRXTElGz/X5J9cYhkZdzTIMW3qRGzn1ZcYSSvWWQFpDEUtPf9o6VoWDawPtuANe8WyS79OctM8CuUV1lESuIMYoPUEz3Fi67CD4FR1iGEDXHtNfjdZfTQp7cvCWPEEvqQR1aAp1D1mjqd6z+wsb5RZzIdT+rCAyRRtAELM262FUbjuhPJKoofCpAgdMirLHJWa6MoZkznx1jwgNDTsU7bVNd+7dryvHT6HLirbbBDjSh1E0IVZ4GBlYlLWDp9Y1a+yNQWiCgBO/9RuBxpkhH64E4PyMIz2g1a7WpXqPhKFkNNXky8aVvRJJ7VO9TdVTAvi0GIvrelpNpWUSJnrLaw1ObSe62za6vuTkABj6x3Wq96UFUBNVSspmneCS754mH6OQRjl8cj7TvkLQ3Jl8D8Cv0rN1rPvwsTZFLto2dZrok+wxbBJ4roER/DPJ4Bw4OYPCMqsO8tuoxooLDXPlrJfceOJs8zRL5rWIHMPeYX5m6xND7abBk+TjIvZBsUv0SaFXItPsJqXcMQ2t9c3Ny/orGRhJaV2UrPAXuYmpW6IAXBySogAVlV/38yX8MKSTApeZW7Hxz88JMTGF6NXuURT3gjmxq7w3GWXDwEr7577UJ9fJXAZXxDxiZzbuSTGQ3hPl+HXESLlIEMZ62uNw=
