language: python
python:
- '3.6'
- nightly
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: ek4TsyGP33lMTqzkhIYv+70bb6LhY5Oy8Te4mqMGbhVvPofnfT17Q6SSVE+tX3zVYxzuvE3gEf+FQ3Xov8z/oU5fcpa/jZCleBEivU7S5rnaUoLhAPZrCkDpkpNg1FM1YQ8ViAGTg9CJY4shCr6nd+yg3fMDk1DJ9TTmF9walfB+jILnl9tdDWIDqwlLpQSQeZOSDdOHRS/8htNRDxq4QrwHIZFyjAaSXGSVVB3VbEkjhbAMKGfqIVgg8QZdJOtonZXg5yEMur5I6SmkkNBSaPQposKyBycPLqWPMsIeXRlfz2Fkh0hV91LGp78Aga2WkqyQEo+y+X3Lg3cQW2bj1m0otlQjd/SlYGzuDx/Zz32MVOfq36fvWAI1cAqPf62pZkS9dtJjcLTGtZIEah7h+1ugQMTwIVX3qsT2IoqhoqySD1wQ0ZGowHRr8vmJ7ykPQfe2OodSsLUs4Qr6rkWC4VyoS6gatrSN4HZbYA6SZVN9tpRj1GK2BInBZjK3NxXAmPFwKwcwuUDrXetGEay+hiwDlfSL2GA/O9cAki3p8OmEkUfEhWpAeDFmJFQRqQnk63/n5x8BeACGo7/iG+vZPPHx3h7/cUafxHJVKb2uhrH2kje4r3PgEuu1No4tz3AXaqB8kh6DQIaN2mnj1d7F/UaObxRYCrwylVPzDaK5/2s=
